### ISSUE TITLE
[1.5.2] Liberation campaign with JF-17. Expected [, got {

### ISSUE THREAD

**Issue by coltonfreeh** [shdwp/dcs_liberation#80] opened 2019-12-30 22:40 UTC
Title, see [DCSLIB1.5.2BUG.txt](https://github.com/shdwp/dcs_liberation/files/4011316/DCSLIB1.5.2BUG.txt) for full output.

**Comment by coltonfreeh** [comment] 2019-12-30 22:41
To note, error occurs upon pressing Commit button in a Naval Intercept Mission Menu.

**Comment by coltonfreeh** [comment] 2019-12-30 22:59
Tested with fresh install. Still occurs. Doesn't matter what type of mission. Deleting save game doesn't help. If I knew how to build the source I'd try to fix it. :/ I haven't worked with Python enough to understand what the hell I'm doing to build it well enough on Windows to get even close.

**Comment by wrycu** [comment] 2019-12-30 23:00
Please hop on the discord so we can talk in realtime - https://discord.gg/XSJbpE

**Comment by wrycu** [comment] 2019-12-30 23:12
Looks like an issue with the JF-17. For now, just create the mission without assigning it and you should be fine.

**Comment by wrycu** [comment] 2019-12-30 23:37
This is an upstream error caused by an inability to parse the payload file.  I've opened https://github.com/pydcs/dcs/issues/26.

**Comment by coltonfreeh** [comment] 2020-01-01 03:27
Well done identifying the bug. Big fan of how quickly you work and the effort you put in.

**Comment by wrycu** [comment] 2020-01-02 02:34
Released 1.5.2.1 with the fix.

**Closed by wrycu** 2020-01-02 02:34 UTC
Labels: bug
