### ISSUE TITLE
[1.5.2.2] F-16 Has No Default Loadouts

### ISSUE THREAD

**Issue by wsethbrown** [shdwp/dcs_liberation#88] opened 2020-01-13 04:28 UTC
The Modding Manual says that you can edit the loadout of planes in missions in the game/game.py file but it doesn't seem to exist any longer.

How can we edit loadouts?

Also, the F-16 has no default loadout, so when spawning in the air (which is sometimes still forced), the F-16 is heavily handicapped.

**Comment by wrycu** [comment] 2020-01-14 23:51
The file is still present in the source code, so you can still edit it.  That being said, the Viper shouldn't be spawning with no loadout - I'll look into fixing that.

**Comment by wrycu** [comment] 2020-01-15 00:38
Confirmed the issue and I think I've got a fix, but I don't own the F-16 so I can't verify. Can you join the Discord (https://discord.gg/evmKtZ) and ping me when you have a chance so I can send the files and we can validate that it starts with an actual payload?

**Comment by wrycu** [comment] 2020-01-16 07:07
Okay, this is fixed. I'll release it shortly - want to get #87 in as well. In the meantime, there's a link in the Discord to grab a release I built but didn't publish on the repo.

**Comment by marcantonio152** [comment] 2020-02-19 03:21
Could you please update the "mod" section so we know how to update the default loadouts for the planes? I found the game.py and db.py files in the source code but I'm not sure how I can get the game to accept my updates

**Comment by tomshackell** [comment] 2020-03-17 17:29
So I did eventually fix this is my local version, for the curious:
- you need to get it compiling from source, the instructions are at [https://github.com/shdwp/dcs_liberation/wiki/Development-guide] but they are not super clear in several places.
- you should then change the payloads for the F-16 to be sensible.
- you then need to change `game.py` so that it uses those payloads.
Overall was about 4-5 hours work.

**Comment by wrycu** [comment] 2020-03-17 18:05
Whoops, sorry. I'll release the build with this corrected after work.

**Comment by marcantonio152** [comment] 2020-03-17 19:44
Would love to get the new release with some instructions on how to change out the loadout! A friend of mine and I have been playing this, and our biggest frustration is we can't choose our own loadout before flying. With the latest DCS updates, we've been having to shut down the aircraft to rearm... it ends up taking a LONG time to get in the air on this campaign because we want to customize our loadout for each mission.

Please let me know how I can change the loadouts! Thanks!!

**Comment by wrycu** [comment] 2020-03-18 00:28
@marcantonio152 can you please create a new issue for updating the instructions? I don't want to lose track of the ask.

Closing this issue as I've uploaded the 1.5.2.3 release.

**Closed by wrycu** 2020-03-18 00:28 UTC
Labels: bug, waiting for release
